### PR TITLE
Fix interest empty list issue

### PR DESCRIPTION
**Pull request by arendarenko**
Fir for #459 459

### CODE REVIEW

**Review by gonzaloebiz — CHANGES_REQUESTED** [review]
This change has nothing related to the interest groups, listId contains the mailchimp list associated to the mailchimp store an has no relation with the interest groups

**Comment by arendarenko** [comment]
hi @gonzaloebiz 
sendSubscribers calls getInterest method: https://github.com/mailchimp/mc-magento2/blob/develop/Model/Api/Subscriber.php#L60 which tries to retrieve listId by storeId https://github.com/mailchimp/mc-magento2/blob/develop/Helper/Data.php#L1003 without any check (for example, if listId is not empty, API method will executed this way: "lists//interest-categories", which will cause this error.

**Review by gonzaloebiz — COMMENTED** [review]
well, on there https://github.com/mailchimp/mc-magento2/blob/develop/Cron/Ecommerce.php#L125 we check if the extension is active, then o there https://github.com/mailchimp/mc-magento2/blob/develop/Cron/Ecommerce.php#L140 we check if you select a mailchimp store.
Each mailchimp store has a list, no way to define a mailchimp store without a list, so you can't have a mailchimp store configured but no list. 
I think the only way to have no list is modify the database by hand

**Comment by gonzaloebiz** [comment]
No news in 22 days

**Comment by ihor-sviziev** [comment]
Hi @gonzaloebiz ,

We have following configuration:
- Default scope:
capture 2019-01-04 at 10 02 53
    - Website 1 (configured for MC store ID: "Website 1", list: "Website 1")
capture 2019-01-04 at 10 04 54
    - Website 2 (configured for MC store ID: "Website 2", list: "Website 2")
capture 2019-01-04 at 10 07 22
    - Website 3 - not configured
capture 2019-01-04 at 10 08 18

Each website has one store view, nothing configured on store view level.

In such configuration looks like for the store related to website 3 somehow we're getting into this issue.
Could you re-check it?

**Pull request closed without merging**
